### ISSUE TITLE
Students can not upload a file if an assignment was posted with a file attachment by the teacher

### ISSUE THREAD

**Issue by amytessitore** [turnitin/moodle-plagiarism_turnitinsim#109]
After installing the 3/3/2021 updated plugin students are no longer able to upload a file as part of an assignment submission if the assignment was posted with a file attachment from the teacher.

Steps to replicate:
Create an assignment as a teacher, post assignment with an attachment, or access an existing assignment that has an attachment
Switch to student
Upload a file for submission to the assignment
The "save changes" button will not function.

Issue appeared immediately after installation of the updated plugin 
<img width="502" alt="TII cant save" src="https://user-images.githubusercontent.com/24849578/110003003-f7b22600-7ce3-11eb-9f89-80b20d8cc661.png">

**Comment by dwinn** [comment]
Hi @amytessitore,

I'm sorry to hear about this issue. We were able to replicate this bug and as such we have released a fix today. Please upgrade to v2021030901.
