### ISSUE TITLE
Turnitin-icon missing from file submission row

### ISSUE THREAD

**Issue by Urpokarhu1** [turnitin/moodle-plagiarism_turnitinsim#115]
Hello,

We have updated plagiarism_turnitinsim in Moodle 3.9 from version 2021011801 to version 2021030901 now we cannot see any Turnitin icons leading to similarity reports in "file submission" row anymore, seems like a bug.

![turnitin1](https://user-images.githubusercontent.com/53904029/114530793-f3b6e380-9c53-11eb-939d-49b8d2f96571.PNG)

![turnitin2](https://user-images.githubusercontent.com/53904029/114530815-f7e30100-9c53-11eb-832c-509e308d3173.png)

**Comment by JMarshall841** [comment]
Hi @Urpokarhu1,

Can you please send an email describing the issue in as much detail as possible to "tiisupport@turnitin.com". This will raise a ticket with our support team who will assist in solving this issue.

Thanks,
Jordan
