### ISSUE TITLE
numerous warnings whenever creating, editing or saving activities

### ISSUE THREAD

**Issue by taraghi** [turnitin/moodle-plagiarism_turnitinsim#127]
Observed in 
- **Moodle version 3.9.9** when debug mod is active
- **Turnitinsim Plugin version: 2021030901**

Turnitin generates numerous warnings whenever creating, editing or saving activities. Generally, these warnings appear whether Turnitin is activated or not.

### Steps to reproduce the warning below: 
Add an Activity or Resource (as a teacher or manager) > Choose any except for Assignment (Tested with: Label, Group Choice, Scheduler) > Add the required information > Save and Return to Course.

![add_activity_resource_1](https://user-images.githubusercontent.com/204101/128343865-f2d25583-e2ea-4f48-b5b6-63f9e575c6e6.png)

### Steps to reproduce the warning below:
Edit any Activity (as a teacher or manager) > Save and Return to Course

![add_activity_1](https://user-images.githubusercontent.com/204101/128344008-f8ba2da3-ed58-4832-a6fb-ab32f3cd7c82.png)

The activity can be saved after clicking Continue and ignoring the warnings.
### Steps to reproduce the warning below:
Add an activity or resource (as teacher or manager) > Assignment > Directly when first creating the assingment  or when editing any existing assignment activity (as teacher or manager), the following warnings appear:

![edit_assignment_2](https://user-images.githubusercontent.com/204101/128344209-4ea16d8b-da1f-4f4b-8206-cdf83470adc3.png)

### Steps to reproduce the warning below:
Save and Return to Course in the Assignment just created, irrespective of whether Turnitin is enabled or not - or simply edit an existing visible assignment activitiy > Save and Return to Course

![visible_assignment_2](https://user-images.githubusercontent.com/204101/128344433-6bea0d3a-8ee5-4165-85f7-85534033feab.png)

### Steps to reproduce the warning below:
Edit a hidden Assignment activity (as teacher or manager) > Save and Return to Course

![hidden_assignment_2](https://user-images.githubusercontent.com/204101/128344553-8197765a-0a3e-4389-96a4-da05aba4d9b1.png)

It is possible to click Continue and the assignment is created or saved normally.
### Steps to reproduce the warning below:
Open a currently open assignment (as student), irrespective of whether Turnitin is enabled or not > Continue to the „add submission“ window 

![before_submission_3](https://user-images.githubusercontent.com/204101/128344647-7133dd9e-8238-4b6a-81ec-798f52de037e.png)

### Steps to reproduce the warning below:
Add a submission file and Save (as student) to the assignment created before, irrespective of whether Turnitin is enabled or not

![add_submission_3](https://user-images.githubusercontent.com/204101/128344725-fc2b4650-3ac7-4cd7-8a75-32876226d59e.png)

### Steps to reproduce the warning below:
Go to the assignment created before (as teacher or manager), no matter if Turnitin is enabled or not > View all submissionsORGo to the assignment created before, irrespective of whether Turnitin is enabled or not (as student) > Edit submission

![edit_submission_warning_4](https://user-images.githubusercontent.com/204101/128344808-75c3f114-0bde-4c80-8975-ccd2e3c40268.png)

**Comment by JMarshall841** [comment]
Hi @taraghi,
We are aware of the deprecation warnings when debug mode is turned on. As the plugin supports multiple versions of moodle we need to continue to use the deprecated methods on the older versions. Once support for moodle 3.8 is dropped we will remove all references to those methods.
