### ISSUE TITLE
PHP Deprecated: Creation of dynamic property plagiarism_turnitinsim_task::$tseula is deprecated 

### ISSUE THREAD

**Issue by acquaalta** [turnitin/moodle-plagiarism_turnitinsim#168]
Hi,

Moodle version: 4.3.2
PHP version: 8.2.13

It seems that every couple of minutes the CRON of the Moodle server sends us the following message:
PHP Deprecated: Creation of dynamic property plagiarism_turnitinsim_task::$tseula is deprecated in [Our path]/moodle/plagiarism/turnitinsim/classes/task.class.php on line 66

Please fix this issue.

**Please note that originally I reported this issue in the repository of the "sibling" plugin:
https://github.com/turnitin/moodle-plagiarism_turnitin/issues/710**
At the time I didn't notice that there are two different plugins, since they have a lot of similarity and a very similar name. The bug also happens in moodle-plagiarism_turnitinsim, of course.

**Comment by acquaalta** [comment]
Please note that in the case of such an issue, which is a CRON message that the client gets and probably can't understand its meaning, it would be great if you until fixing the issue completely by releasing a new version of the plugin, you could at least explain if and how it affects the functionality of the plugin.

Thanks

**Comment by jack-tii** [comment]
Fix for this will go out in our October release. Thanks for bringing this to our attention.
